apiVersion: v1
kind: ServiceAccount
metadata:
  name: hugin-sa
  namespace: hugin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hugin-sa
  namespace: hugin
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hugin-role-binding
  namespace: hugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hugin-sa
subjects:
  - kind: ServiceAccount
    name: hugin-sa
    namespace: hugin