spring:
  application.name: hugin
management:
  info:
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  my_env_var: ${MY_VAR}